js也存在块级作用域
    with从对象中创建出的作用域仅在with声明中而非外部作用域中有效
    try/catch中的catch分句会创建一个块作用域，声明的错误变量仅在catch内部有效
